---
title: "CLustering/ Deep learning of Food preference data"
author: "Dr. Shirin Glander"
date: '`r Sys.Date()`'
output:
  prettydoc::html_pretty:
    theme: tactile
    highlight: github
---

```{r}
library(fivethirtyeight)

str(food_world_cup)
```

http://www.r-tutor.com/deep-learning/introduction

https://www.r-bloggers.com/r-for-deep-learning-i-build-fully-connected-neural-network-from-scratch/

https://cran.r-project.org/web/packages/nnet/nnet.pdf

https://cran.r-project.org/web/packages/h2o/h2o.pdf

---

https://cran.r-project.org/web/packages/neuralnet/neuralnet.pdf

```{r}
library(neuralnet)
AND <- c(rep(0,7),1)
OR <- c(0,rep(1,7))
binary.data <- data.frame(expand.grid(c(0,1), c(0,1), c(0,1)), AND, OR)
print(net <- neuralnet(AND+OR~Var1+Var2+Var3, binary.data, hidden=0,rep=10, err.fct="ce", linear.output=FALSE))
plot(net)

data(infert, package="datasets")
print(net.infert <- neuralnet(case~parity+induced+spontaneous, infert,err.fct="ce", linear.output=FALSE, likelihood=TRUE))
plot(net.infert)

gwplot(net.infert, selected.covariate="parity")
confidence.interval(net.infert)
prediction(net.infert)


Var1 <- runif(50, 0, 100) 
sqrt.data <- data.frame(Var1, Sqrt=sqrt(Var1))
print(net.sqrt <- neuralnet(Sqrt~Var1,  sqrt.data, hidden=10, 
                  threshold=0.01))
compute(net.sqrt, (1:10)^2)$net.result
plot(net.sqrt)
```

https://cran.r-project.org/web/packages/darch/darch.pdf

```{r}
library(darch)



```

https://cran.r-project.org/web/packages/deepnet/deepnet.pdf

------------------

<br>

```{r echo=FALSE, message=FALSE, warning=FALSE, fig.width=6, fig.height=4, fig.align="center", cache=FALSE}
sessionInfo()
```
